<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Official Transcript - {{ $student->student_code }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #1a56db; }
        .student-info { margin-bottom: 20px; width: 100%; }
        .student-info td { padding: 5px; }
        .student-label { font-weight: bold; width: 150px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f3f4f6; border: 1px solid #d1d5db; padding: 8px; text-align: left; }
        td { border: 1px solid #d1d5db; padding: 8px; }
        .period-header { background-color: #e5e7eb; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; padding: 10px 0; border-top: 1px solid #d1d5db; }
        .stats { margin-top: 20px; text-align: right; }
        .stats-item { display: inline-block; margin-left: 20px; font-weight: bold; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>NovaTech University</h1>
        <p>Official Academic Transcript</p>
    </div>

    <table class="student-info">
        <tr>
            <td class="student-label">Student Name:</td>
            <td>{{ $student->user->name }}</td>
            <td class="student-label">Student ID:</td>
            <td>{{ $student->student_code }}</td>
        </tr>
        <tr>
            <td class="student-label">Major:</td>
            <td>{{ $student->major->name }}</td>
            <td class="student-label">Department:</td>
            <td>{{ $student->major->department->name }}</td>
        </tr>
        <tr>
            <td class="student-label">Degree:</td>
            <td>Bachelor of Science</td>
            <td class="student-label">Date Generated:</td>
            <td>{{ $generated_at }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Course Title</th>
                <th>Credits</th>
                <th>Grade</th>
                <th>Grade Point</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transcript as $semester)
                <tr class="period-header">
                    <td colspan="5">{{ $semester['period'] }} (GPA: {{ number_format($semester['semester_gpa'], 2) }})</td>
                </tr>
                @foreach($semester['courses'] as $course)
                    <tr>
                        <td>{{ $course['course_code'] }}</td>
                        <td>{{ $course['course_name'] }}</td>
                        <td align="center">{{ $course['credits'] }}</td>
                        <td align="center">{{ $course['grade'] }}</td>
                        <td align="center">{{ number_format($course['grade_point'], 1) }}</td>
                    </tr>
                @endforeach
            @endforeach
        </tbody>
    </table>

    <div class="stats">
        <div class="stats-item">Total Credits: {{ $total_credits }}</div>
        <div class="stats-item">Cumulative GPA: {{ number_format($cgpa, 2) }}</div>
    </div>

    <div class="footer">
        <p>This is an official document generated by NovaTech Student Information System.</p>
        <p>&copy; {{ date('Y') }} NovaTech University. All Rights Reserved.</p>
    </div>
</body>
</html>
