<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    /**
     * GET /api/subjects
     * Optional filter: ?department_id=1
     */
    public function index(Request $request)
    {
        $query = Subject::query();

        if ($request->filled('department_id')) {
            $query->where('department_id', $request->department_id);
        }

        $subjects = $query->latest('id')->get();

        return response()->json([
            'success' => true,
            'data' => $subjects
        ], 200);
    }

    /**
     * POST /api/subjects
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'department_id' => 'required|integer|exists:departments,id',
            'subject_name'  => 'required|string|max:255',
            'description'   => 'nullable|string',
            'credit'        => 'required|integer|min:1',
        ]);

        // ✅ code is auto-generated by Subject model
        $subject = Subject::create($validated);

        return response()->json([
            'success' => true,
            'message' => 'Subject created successfully',
            'data' => $subject
        ], 201);
    }

    /**
     * GET /api/subjects/{id}
     */
    public function show($id)
    {
        $subject = Subject::with(['majorSubjects', 'department'])->findOrFail($id);

        return response()->json([
            'success' => true,
            'data' => $subject
        ], 200);
    }

    /**
     * PUT /api/subjects/{id}
     */
    public function update(Request $request, $id)
    {
        $subject = Subject::findOrFail($id);

        $validated = $request->validate([
            'department_id' => 'required|integer|exists:departments,id',
            'subject_name'  => 'required|string|max:255',
            'description'   => 'nullable|string',
            'credit'        => 'required|integer|min:1',
        ]);

        // ❌ do NOT update code from frontend
        $subject->update($validated);

        return response()->json([
            'success' => true,
            'message' => 'Subject updated successfully',
            'data' => $subject
        ], 200);
    }

    /**
     * DELETE /api/subjects/{id}
     */
    public function destroy($id)
    {
        $subject = Subject::findOrFail($id);

        // Optional safety check
        // if ($subject->majorSubjects()->exists()) {
        //     return response()->json([
        //         'success' => false,
        //         'message' => 'Cannot delete subject because it is used by majors.'
        //     ], 409);
        // }

        $subject->delete();

        return response()->json([
            'success' => true,
            'message' => 'Subject deleted successfully'
        ], 200);
    }
}
